security:
  oauth2:
    client:
      clientId: #add this
      clientSecret: #add this
      access-token-uri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      token-name: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me      
     
    
