security:
  oauth2:
    client:
      clientId: #add this
      clientSecret: #add this
      access-token-uri: https://graph.facebook.com/oauth/access_token  #https://github.com/login/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth #https://github.com/login/oauth/authorize
      token-name: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me      #https://api.github.com/user
     
    
